### ISSUE TITLE
edit cron in existing hook

### ISSUE THREAD

**Issue by logemann** [bigcompany/hook.io#139]
Editing a cron expression on an existing hook cleans the previous entered cron expression. Pre-selecting the current value would be helpful.

Also it would be nice if can define my local timezone and enter a cron expression which makes sense in my local time. Right now i need to calculate this myself and if our daylight saving time changes, i likely need to adjust all cron expressions.

**Comment by Marak** [comment]
Good catch @logemann 

I've found this and a couple of other regressions on the admin form from the previous re-factor. Should already be fixed in `master`. Will be in the next deploy.

I like your suggestion about time/zones / improving the visibility of cron executions. The editor we use I built myself ( https://github.com/marak/cron-editor ). I will see what we can to do make this experience better.

**Comment by Marak** [comment]
RE: #292
