### ISSUE TITLE
Golang Support

### ISSUE THREAD

**Issue by cathalgarvey** [bigcompany/hook.io#157]
Hey all, great looking service! And I appreciate that it's Open Source. :)

What are the barriers to Golang support? Compilation is very rapid, so much so that you can even add a shebang like `#!/usr/bin/env go run` and treat programs like "scripts" (though that's wasteful..). It's fairly safe, and will prevent compilation on non-typesafe code for the most part. It's very efficient and can scale to thousands of connections even when run "bare" without a fronting webserver.

Google App Engine supports Go but disables the `unsafe` and `reflect` libraries; presumably these are useful in escaping sandboxes or causing server woes.

Thoughts?

**Comment by Marak** [comment]
Hi!

Related #142 

The main barrier we have right now is that we don't have any direct support for using compiled languages in our services. We have no compile step or a safe place to store compiled binaries ( yet ).

If you are saying that it's possible to implement Go support without making any major modifications to our stack ( using the scripts method described above ), it could be a good first step.

If you look at how the other languages are implementing in https://github.com/bigcompany/hook.io/tree/master/bin you can get an idea for how it would be setup.

I'm a fan of adding Golang to the platform. I just don't want to commit to having to implement support for compiled languages (right now) because it will increase our complexity.

Do you think using Golang "scripts" is an acceptable first step?

A few of us idle in #hook.io on irc.freenode.net. Please feel free to join us there.

**Comment by Marak** [comment]
@cathalgarvey - We've posted a $100 bounty for resolving this issue.

https://www.bountysource.com/issues/27059758-golang-support

**Comment by Marak** [comment]
Closing issue.

This is no longer applicable, as all core spawning logic has been moved to: https://github.com/stackvana/stack

If anyone is interested in adding Go support, please file a new issue at: https://github.com/stackvana/stack/issues/new

Any changes to `stack` will propagate down-stream to hook.io
