### ISSUE TITLE
Still getting 10 second timeout limit on paid account

### ISSUE THREAD

**Issue by Galeforce1** [bigcompany/hook.io#216]
Still getting 10 second timeout limit on paid account. Isn't it supposed to be configurable?

Thanks.

**Comment by Marak** [comment]
Ahh! Sorry about that. I found a bug in the view which is not showing the form input.

This is referencing legacy variable: https://github.com/bigcompany/hook.io/blob/master/view/admin.js#L216

Should be a one-line fix.

I can make a quick change to enable it / up the timeouts for your service.

What's the nature of the service in that it requires more than 10 seconds? Most services should execute well under the 10 second limit.

**Comment by Galeforce1** [comment]
Hi Marak, its an GET query to an API that sometimes takes longer - don't know why.

**Comment by Marak** [comment]
We have a few issues around paid accounts activating features. Really need to fix that.

I've set the service on your account to have a 60 second timeout. You'll need to hit the `/refresh` endpoint once on the hook in order to update.

Should then wait 60 seconds until timeout. Sorry again. Let me know
